
name: Beana CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Deploy to Vercel Action
      uses: BetaHuhn/deploy-to-vercel-action@v1
      with:
        GITHUB_TOKEN: ${{ secrets.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 }}
        VERCEL_TOKEN: ${{ secrets.nmx36ni8l2vj6oF3sLBxVLTL }}
        VERCEL_ORG_ID: ${{ secrets.RhZz8MUxNYlkFUYGDkONEuGj }}
        VERCEL_PROJECT_ID: ${{ secrets.prj_PxhMP9RnWxDJCHSx6CVmDmQAfXJH }}
