name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.RhZz8MUxNYlkFUYGDkONEuGj }}
  VERCEL_PROJECT_ID: ${{ secrets.prj_PxhMP9RnWxDJCHSx6CVmDmQAfXJH }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.nmx36ni8l2vj6oF3sLBxVLTL}}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.nmx36ni8l2vj6oF3sLBxVLTL}}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.nmx36ni8l2vj6oF3sLBxVLTL}}